close all;
clear;
[x,fs]=audioread('outputfile.wav');
 sound(x,fs);
 pause(8);
len_x=8*fs;                                                     
x = x(1:len_x,1);
T=1/fs;
t = T:T:len_x*T;
figure( 'Name','音频信号分析','Position',[50,350,400,300] );         
subplot( 2,1,1 );                                         
plot( t,x );                                              
axis([0 7 -0.5 0.5]);
title( '时域波形图' );                                               
xlabel( '时间(s)' ); ylabel( '幅值' );                               

fft_N = 2^nextpow2( len_x);                                    
X = fft( x,fft_N );                                   
X_AMP = abs( X );                                     
f = fs*(0:fft_N/2-1)/fft_N;                                     
X_HALF = X_AMP(1:(fft_N/2));                          

subplot( 2,1,2 );                                               
plot( f,X_HALF );                                          
title( '频谱' );                                                
xlabel( '频率(Hz)' );ylabel('幅度');                            
axis( [0 2000 0 600] ); 

fc=max(f);
FS=fc/20;
TT=1/FS;
tt = T:TT:len_x*T
xFS = interp1( t,x,tt );                              
len_xFS = length( xFS );                              
figure( 'Name','欠采样的音频信号','Position',[450,350,400,300] );
subplot( 2,1,1 );                         
plot( tt,xFS );                                            
title( '欠采样时域波形图' );                        
xlabel( '时间(s)' ); ylabel( '幅值' );
axis([0 7 -0.5 0.5]);
sound(xFS,FS);
pause(8);
fft_N = 2^nextpow2( len_xFS);                                    
XFS = fft( xFS,fft_N );                                  
XFS_AMP = abs( XFS );                                     
ff = FS*(0:fft_N/2-1)/fft_N;                                     
XFS_AMP_HALF = XFS_AMP(1:(fft_N/2));
subplot( 2,1,2 );                                               
plot( ff,XFS_AMP_HALF );                                          
title( '欠采样频谱' );                                                
xlabel( '频率(Hz)' );ylabel('幅度');                            
axis( [0 1000 0 20] ); 

FS1=fc*2;
TT1=1/FS1;
tt1 = T:TT1:len_x*T;
xFS1 = interp1( t,x,tt1 );                              
len_xFS1 = length( xFS1 );                              
figure( 'Name','合理采样的音频信号','Position',[450,350,400,300] );
subplot( 2,1,1);                         
plot( tt1,xFS1 );                                            
title( '合理采样时域波形图' );                       
xlabel( '时间(s)' ); ylabel( '幅值' );
axis([0 7 -0.5 0.5]);
 sound(xFS1,FS1);
 pause(8);
fft_N = 2^nextpow2( len_xFS1);                                    
XFS1 = fft( xFS1,fft_N );                                   
XFS1_AMP = abs( XFS1 );                                     
ff1 = FS1*(0:fft_N/2-1)/fft_N;                                     
XFS1_AMP_HALF = XFS1_AMP(1:(fft_N/2));                         
subplot( 2,1,2 );                                              
plot( ff1,XFS1_AMP_HALF );                                          
title( '频谱' );                                                
xlabel( '频率(Hz)' );ylabel('幅度');                            
axis( [0 2000 0 600] ); 


fc=max(f);
FS2=fc*4;
TT2=1/FS2;
tt2 = T:TT2:len_x*T;
xFS2 = interp1( t,x,tt2 );                              
len_xFS2 = length( xFS2 );                              
figure( 'Name','过采样的音频信号','Position',[450,350,400,300] );
subplot( 2,1,1 );                         
plot( tt2,xFS2 );                                            
title( '过采样时域波形图' );                        
xlabel( '时间(s)' ); ylabel( '幅值' );
axis([0 7 -0.5 0.5]);
sound(xFS2,FS2);
pause(8);
fft_N = 2^nextpow2( len_xFS2);                                   
XFS2 = fft( xFS2,fft_N );                                   
XFS2_AMP = abs( XFS2 );                                   
fs2 = FS2*(0:fft_N/2-1)/fft_N;                                   
XFS2_AMP_HALF = XFS2_AMP(1:(fft_N/2));                       

subplot( 2,1,2 );                                              
plot( fs2,XFS2_AMP_HALF );                                       
title( '频谱' );                                                
xlabel( '频率(Hz)' );ylabel('幅度');                           
axis( [0 2000 0 600] ); 

noise = 1.5*sin(2*pi*30*10^3*tt2);                               
signal_noise =xFS2+ noise(1:len_xFS2);                
sound(signal_noise,FS2);
pause(8);
figure( 'Name','叠加30k正弦信号噪声后的音从、频信号','Position',[450,350,400,300] );
subplot(2,1,1);plot(tt2,signal_noise);
signal_noise_pp=fft( signal_noise,fft_N );
signal_noise_pp_AMP = abs( signal_noise_pp ); 
pp_AMP_HALF = signal_noise_pp_AMP(1:(fft_N/2)); 
subplot(2,1,2);plot(fs2,pp_AMP_HALF);

WP=2*pi*1000;
WS=2*pi*3000;
ap=1;
as=60;
[b1,a1]=Butter_Low(WP,WS,ap,as,FS2);
signal_lvbo=filter(b1,a1,signal_noise);
figure('Name','滤波后音频波形','Position',[450,10,400,300]);
subplot(2,1,2);
plot(tt2,signal_lvbo);
title('滤波后音频波形');
xlabel('时间（s）');
ylabel('幅值');
subplot(2,1,1);
plot(tt2,signal_noise);
title('滤波前音频波形');
xlabel('时间（s）');
ylabel('幅值');
SIGNAL_LVBO=fft(signal_lvbo,fft_N);
SIGNAL_LVBO_AMP_HALF=abs(SIGNAL_LVBO(1:(fft_N/2)));
signal_lvbo1=xFS2 ;
figure('Name','滤波前后音频信号频谱比较','Position',[850,10,400,300]);
subplot(2,1,1);
plot(fs2,pp_AMP_HALF);
title('滤波前音频频谱');
xlabel('频率（Hz）');
ylabel('幅值');
axis([0 35*10^3 0 100]);
subplot(2,1,2);
plot(fs2,SIGNAL_LVBO_AMP_HALF);
title('滤波后音频频谱');
xlabel('频率（Hz）');
ylabel('幅值');
axis([0 35*10^3 0 100]);
sound(signal_lvbo1,FS2);

